#!/bin/bash

set -e
set -o pipefail

. ./bin/aws/utils

check_eksctl_installed

. .env

eksctl utils associate-iam-oidc-provider \
  --region "$AWS_REGION" \
  --cluster "$EKS_CLUSTER_NAME" \
  --approve
