#!/bin/bash

set -e
set -o pipefail

. ./bin/aws/utils

check_eksctl_installed

. .env

AWS_PROFILE=eksadmin eksctl create iamserviceaccount \
  --name "$IAM_SERVICE_ACCOUNT" \
  --region "$AWS_REGION" \
  --cluster "$EKS_CLUSTER_NAME" \
  --attach-policy-arn "$POLICY_ARN" \
  --approve \
  --override-existing-serviceaccounts
