#!/bin/bash

echo "[RUNNERS] [EKS] Creating elasticache replication group."

export VPC_ID=$(./bin/aws/ec2/vpcs/describe)
export EKS_SECURITY_GROUP_ID=$(./bin/aws/ec2/security-groups/describe)
export CACHE_SUBNET_GROUP_NAME="${EKS_CLUSTER_NAME}-subnet-group"
export SECURITY_GROUP_IDS="${EKS_SECURITY_GROUP_ID}"

./bin/aws/ec/redis/replication-group/create

REPLICATION_GROUP_STATUS=""

while [ "$REPLICATION_GROUP_STATUS" != "available" ]; do
  echo "[RUNNERS] [RDS] Waiting for redis cluster to be created..."

  REPLICATION_GROUP_STATUS=$(bin/aws/ec/redis/replication-group/status)

  sleep 10
done

echo "[RUNNERS] [EKS] Redis cluster has been created."
