#!/bin/bash

set -e
set -o pipefail

. ./bin/aws/utils

check_eksctl_installed

. .env

echo "[AWS] [EKS] Setting up cluster."

# https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI

AWS_PROFILE=eksadmin eksctl create cluster \
  --name "$EKS_CLUSTER_NAME" \
  --version "$EKS_CLUSTER_VERSION" \
  --region "$AWS_REGION" \
  --nodegroup-name "$EKS_NODE_GROUP_NAME" \
  --node-type "$EKS_NODE_TYPE" \
  --nodes "$EKS_NODE_COUNT" \
  --zones "$EKS_ZONES"

echo "[AWS] [EKS] Completed setting up cluster."
