#!/bin/bash

set -e
set -o pipefail

. ./bin/aws/utils

check_aws_cli_installed

. .env

echo "[UTILS] [EC2] [Security Groups] Describing security group for VPC ${VPC_ID}." >&2

aws ec2 describe-security-groups \
  --filters "Name=vpc-id,Values=${VPC_ID}" "Name=group-name,Values=eks-cluster-sg-${EKS_CLUSTER_NAME}-*" \
  --query "SecurityGroups[0].GroupId" \
  --output text
