#!/bin/bash

function check_aws_cli_installed {
  echo "[UTILS] Checking AWS CLI is installed." >&2

  if ! command -v aws &> /dev/null; then
    echo "AWS CLI is not installed. Please install it first. https://aws.amazon.com/cli/" >&2
    exit 1
  fi

  echo "[UTILS] Confirmed AWS CLI is installed." >&2
}

function check_helm_installed {
  echo "[UTILS] Checking Helm is installed." >&2

  if ! command -v helm &> /dev/null; then
    echo "hl could not be found. Please install it first. https://helm.sh/" >&2
    exit 1
  fi

  echo "[UTILS] Confirmed Helm is installed." >&2
}

function check_kubectl_installed {
  echo "[UTILS] Checking kubectl is installed." >&2

  if ! command -v helm &> /dev/null; then
    echo "kubectl could not be found. Please install it first. https://kubernetes.io/docs/reference/kubectl/" >&2
    exit 1
  fi

  echo "[UTILS] Confirmed kubectl is installed." >&2
}

function check_eksctl_installed {
  echo "[UTILS] Checking eksctl is installed." >&2

  if ! command -v eksctl &> /dev/null; then
    echo "eksctl could not be found. Please install it first. https://eksctl.io/" >&2
    exit 1
  fi

  echo "[UTILS] Confirmed eksctl is installed." >&2
}

function check_docker_installed {
  echo "[UTILS] Checking docker is installed." >&2

  if ! command -v docker &> /dev/null; then
    echo "Docker could not be found. Please install it first. https://www.docker.com/" >&2
    exit 1
  fi

  echo "[UTILS] Confirmed docker is installed." >&2
}

LOG_CONTEXT=""

log() {
  local level="$1"
  shift

  local datetime=$(date +"%Y-%m-%d %H:%M:%S")
  local message="$@"

  echo "[$datetime] [$level] $LOG_CONTEXT $message" >&2
}

info() {
  log "INFO" "$@"
}

error() {
  log "ERROR" "$@"
}

set_log_context() {
  LOG_CONTEXT="$@"
}
