#!/bin/bash

set -e
set -o pipefail

. ./bin/aws/utils

check_aws_cli_installed

. .env

echo "[UTILS] [EC2] [VPCS] Describing VPC for ${EKS_CLUSTER_NAME}." >&2

aws ec2 describe-vpcs \
  --filter "Name=tag:alpha.eksctl.io/cluster-name,Values=${EKS_CLUSTER_NAME}" \
  --query "Vpcs[0].VpcId" \
  --output text \
  --no-cli-pager
