#!/bin/bash

set -e
set -o pipefail

. ./bin/aws/utils

check_docker_installed

args=()

while test $# -gt 0; do
        case $1 in
        --tag) tag=$2; shift;;
        *) args+=("$1");;
        esac
        shift
done

set -- "${args[@]}"

. .env

docker push "$ECR_URI":"$tag"
