#!/bin/sh

. .env

. $AWS_SCRIPTS_BASE_DIR/aws/utils

set_log_context "[UTILS] [EC] [REPLICATION GROUP]"

info "Deleting elasticache replication group."

aws elasticache delete-replication-group \
  --replication-group-id "$AWS_REPLICATION_GROUP_ID" \
  --no-cli-pager

info "[UTILS] [EC] [REPLICATION GROUP] Scheduled deleting elasticache replication group."
