#!/bin/bash

set -e
set -o pipefail

. .env

. $AWS_SCRIPTS_BASE_DIR/aws/utils

check_aws_cli_installed

set_log_context "[UTILS] [EC]"

info "Creating elasticache subnet group."

cmd="aws elasticache create-cache-subnet-group"

cache_subnet_group_name="${AWS_EC_SUBNET_GROUP_NAME:-}"
cache_subnet_group_description="${AWS_EC_SUBNET_GROUP_DESCRIPTION:-}"
subnet_ids="${AWS_VPC_SUBNET_IDS:-}"

[[ -n "$cache_subnet_group_name" ]] && cmd+=" --cache-subnet-group-name \"$cache_subnet_group_name\""
[[ -n "$cache_subnet_group_description" ]] && cmd+=" --cache-subnet-group-description \"$cache_subnet_group_description\""
[[ -n "$subnet_ids" ]] && cmd+=" --subnet-ids \"$subnet_ids\""

cmd+=" --no-cli-pager"

eval $cmd

info "Completed creating elasticache subnet group."
