#!/bin/bash

set -e
set -o pipefail

. .env

. $AWS_SCRIPTS_BASE_DIR/aws/utils

check_aws_cli_installed

set_log_context "[UTILS] [EC] [SUBNET GROUP]"

info "Delete elasticache subnet group. ${AWS_ELASTICACHE_SUBNET_GROUP_ID}"

aws elasticache delete-cache-subnet-group \
  --cache-subnet-group-name "$AWS_ELASTICACHE_SUBNET_GROUP_ID" \
  --no-cli-pager

info "Deleted elasticache subnet group. ${AWS_ELASTICACHE_SUBNET_GROUP_ID}"
