#!/bin/sh

. .env

echo "[AWS] [EKS] Installing local dependencies."

./bin/aws/eks/install-dependencies

echo "[AWS] [EKS] Completed installing local dependencies."

echo "[AWS] [EKS] Associating IAM provider."

./bin/aws/eks/associate-iam-provider

echo "[AWS] [EKS] Completed associating IAM provider."

echo "[AWS] [EKS] Creating service account."

./bin/aws/iam/create-service-account

echo "[AWS] [EKS] Completed creating service account."
